# Generated by Django 2.2.5 on 2020-02-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='Website',
        ),
    ]
